import Navigation from "@/components/Navigation";
import "./globals.css";
import { Metadata } from "next";
import QueryClienteProvider from '@/components/RootLayout'
import PiePagina from '@/components/PiePagina'

export const metadata: Metadata = {
  title: "Dime Legends",
  description: "Generated by create next app",
  authors: {
    name: "Milton Aguilar",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className="bg-zinc-900 text-white">
        <QueryClienteProvider>
          <Navigation />
          <main>{children}</main>
          <PiePagina />
        </QueryClienteProvider>
      </body>
    </html>
  );
}
