"use client"
import Navigation from "@/components/Navigation";
import "./globals.css";
import { Metadata } from "next";
import { QueryClientProvider } from '@tanstack/react-query'
import { queryClient } from '../lib/queryclient'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  authors: {
    name: "Milton Aguilar",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <head>
        <link rel="icon" href="../static/logo.ico" />
      </head>
      <body className="bg-zinc-900 text-white">
        <QueryClientProvider client={queryClient} >
          <Navigation />
          <main>{children}</main>
        </QueryClientProvider>
      </body>
    </html>
  );
}
